// Each preset defines every variable the UI themes off of. Keeping the same
// shape as the server's default theme means presets and custom colors can
// be swapped in and out interchangeably.

export const presets = [
  {
    name: "Dry Dock",
    colors: {
      bg: "#0a1420",
      surface: "#0f1c2e",
      surfaceRaised: "#15263c",
      border: "#1e344f",
      text: "#e7eef5",
      textMuted: "#84a0ba",
      sidebarBg: "#071019",
      sidebarText: "#c2d3e3",
      sidebarActive: "#1e344f",
      primary: "#0099ff",
      primaryText: "#ffffff",
      accent: "#ffb454",
      success: "#3ecf8e",
      warning: "#ffb454",
      danger: "#ff5d5d",
    },
  },
  {
    name: "Deep Sea",
    colors: {
      bg: "#0b1520",
      surface: "#102030",
      surfaceRaised: "#152a3d",
      border: "#1f3a52",
      text: "#e4eef5",
      textMuted: "#7fa1bb",
      sidebarBg: "#081019",
      sidebarText: "#9fc0d6",
      sidebarActive: "#152a3d",
      primary: "#28c7d6",
      primaryText: "#03191c",
      accent: "#ff8a5c",
      success: "#3ecf8e",
      warning: "#f5c451",
      danger: "#ff6161",
    },
  },
  {
    name: "Graphite",
    colors: {
      bg: "#17181a",
      surface: "#1f2022",
      surfaceRaised: "#28292c",
      border: "#35363a",
      text: "#eceded",
      textMuted: "#9a9b9f",
      sidebarBg: "#101112",
      sidebarText: "#c7c8cb",
      sidebarActive: "#28292c",
      primary: "#b7bcc6",
      primaryText: "#111214",
      accent: "#e8b34f",
      success: "#5cc98f",
      warning: "#e8b34f",
      danger: "#e2584f",
    },
  },
  {
    name: "Quay",
    colors: {
      bg: "#faf6ef",
      surface: "#ffffff",
      surfaceRaised: "#f3ede1",
      border: "#e3d9c6",
      text: "#2c2620",
      textMuted: "#7a6f5e",
      sidebarBg: "#2c2620",
      sidebarText: "#e3d9c6",
      sidebarActive: "#463c30",
      primary: "#c1552c",
      primaryText: "#ffffff",
      accent: "#2f6f5e",
      success: "#2f8f5e",
      warning: "#c1552c",
      danger: "#b23a3a",
    },
  },
  {
    name: "Signal",
    colors: {
      bg: "#0e0f13",
      surface: "#16181d",
      surfaceRaised: "#1e2027",
      border: "#2a2d35",
      text: "#eef0f4",
      textMuted: "#8e93a0",
      sidebarBg: "#0a0b0e",
      sidebarText: "#b4b9c4",
      sidebarActive: "#1e2027",
      primary: "#7c5cff",
      primaryText: "#ffffff",
      accent: "#00e5a0",
      success: "#00e5a0",
      warning: "#ffcf5c",
      danger: "#ff5c7c",
    },
  },
];

export const colorFields = [
  { key: "bg", label: "Page background", group: "Surfaces" },
  { key: "surface", label: "Panel background", group: "Surfaces" },
  { key: "surfaceRaised", label: "Raised panel", group: "Surfaces" },
  { key: "border", label: "Borders", group: "Surfaces" },
  { key: "text", label: "Primary text", group: "Text" },
  { key: "textMuted", label: "Muted text", group: "Text" },
  { key: "sidebarBg", label: "Sidebar background", group: "Sidebar" },
  { key: "sidebarText", label: "Sidebar text", group: "Sidebar" },
  { key: "sidebarActive", label: "Sidebar active item", group: "Sidebar" },
  { key: "primary", label: "Primary / links", group: "Accents" },
  { key: "primaryText", label: "Text on primary", group: "Accents" },
  { key: "accent", label: "Accent", group: "Accents" },
  { key: "success", label: "Success", group: "Status" },
  { key: "warning", label: "Warning", group: "Status" },
  { key: "danger", label: "Danger", group: "Status" },
];
